### PR TITLE
Update index.js Issue #1175

### PR DESCRIPTION
**Pull request by rvbatista**
Issue #1175
should be something like this, but I was not able to test.

### CODE REVIEW

**Comment by rvbatista** [comment]
I'm not sure, you see depends on the variable type also, INT should use WriteRegister, and any double REAL, DINT, etc.. should always use WriteRegisters.

As fuxa was only using WriteRegisters, I think that it's interesting to have a user accessible setting to control this behavior.

Fragment feature is already used by Modbus?

**Comment by unocelli** [comment]
The Problem is that value is a bytes array, 
`var _writeMemory = function (memoryAddress, start, value) {`

Int16, Uint16 = 2 bytes
Int32, UInt32 = 4 bytes
Bool = byte

If we define that 1-2 with WriteRegister and 4-8 with WriteRegisters will work for every device? is modbus standard?

**Comment by rvbatista** [comment]
For me both should work, but by specification there is the function to write single register (WriteRegister) and Write Multiple Registers (WriteRegisters) both are 16 bits based for each register.

**Comment by unocelli** [comment]
Thanks a lot.

**Pull request merged**
