### PR TITLE
Feat/webcam Add web player for monitor

### PR DESCRIPTION
**Pull request by rikugun**
add monitor event to shapes, use xgplayer to play live media ,such like http-flv,mp4 .

add a shape with new monitor event
2591709865931_ pic
2581709865911_ pic

when click shapes show dialog

2571709865845_ pic

tested media
```
http://s2.pstatp.com/cdn/expire-1-M/byted-player-videos/1.0.0/xgplayer-demo.mp4

https://mister-ben.github.io/videojs-flvjs/bbb.flv
```

### CODE REVIEW

**Comment by unocelli** [comment]
Hi, Amazing, I love it. 
Why didn't you use a more popular library like Video.js or Plyr?

**Review by unocelli — CHANGES_REQUESTED** [review]
Thank you for your pull request! Overall, it looks great. One small suggestion I have is regarding the use of double quotes instead of single quotes in some parts of the code. It's a good practice to consistently use single quotes for string literals in JavaScript.

**Comment by rikugun** [comment]
> Hi, Amazing, I love it. Why didn't you use a more popular library like Video.js or Plyr?

xgplayer compatibility is better， and http-flv format is popular for live media. xgplayer belong to  the bytedance who devlope tiktok , by the way .

[xgplayer](https://github.com/bytedance/xgplayer)

**Comment by unocelli** [comment]
Thanks again!

**Pull request merged**
