### PR TITLE
feature:  Electron App Support

### PR DESCRIPTION
**Pull request by rikugun**
Use Electron package as a appliction 

[also see ](https://www.electronjs.org/docs/latest/tutorial/tutorial-packaging)

tested in Mac M1,Mac Intel.
runtime data storage in  process.env.APPDATA 

OSX: ${HOME}/Library/Application Support/fuxa-app  
Linux ${HOME}/.local/share/fuxa-app
 
2871714006306_ pic
2851714006278_ pic
2861714006288_ pic

----
# Build Server and Client First
```
cd server 
npm i
cd ../client
npm i
npm run build
````

# Packaging
```
cd app
npm i
npm run package
```

### CODE REVIEW

**Comment by rikugun** [comment]
tested in windows10 

WeChat6761763a156dc09403af414af2b61e3c

**Comment by unocelli** [comment]
Hi, I am testing on node v18.18.2, I am missing something?
image

**Comment by rikugun** [comment]
> Hi, I am testing on node v18.18.2, I am missing something? image

you must build server and client first

**Comment by unocelli** [comment]
The error came from server. with which version of node did you try?

**Comment by rikugun** [comment]
18.20.2

image

**Comment by rikugun** [comment]
tested in debian11 aarch64

3001716346472_ pic_hd

**Comment by unocelli** [comment]
Hi, sorry for the delay!
I installed node version 18 and it works perfectly. Fantastic! Great work and thank you very much :heart:

**Pull request merged**
