### PR TITLE
Input gauge - missing key functionality

### PR DESCRIPTION
**Pull request by algismo**
Key changes as described in the issue #451.

### CODE REVIEW

**Comment by algismo** [comment]
Hi,

I have made a pull request of the implementation I have done for my own needs. Please take a look at let me know what you think.
There are a few places I am not 100% happy:

1. Unit information. Now this is appended to the input as text (like in regular text element), but then unit info must be removed when input field is focused for editing and before applying tag value. My initial idea was to append <div> beside the input element in the editor and keep unit info there, but that was not straightforward since you have not opened your SvgEditor extension file, where the html input is defined.

2. "flex-input" inputType and gauge dlgType. I am reusing flex-input with type "unit", but then in case of input gauge, I also need to show Min/Max fields. I did a hack to find this out in method "isInputMinMax()". Let me know if you will have any better idea how to make this more clean.

3. There is a strange issue when input dialog is enabled and when jumping between input fields with exactly the same value. Then "current input value" disappears since it has not changed (ng model does some nasty thing here my guess). Since it is very corner case, I left it as it is for time being. 

Algirdas

**Comment by unocelli** [comment]
Hi, Thank you for the PR! It looks good.
I do some tests with it before merging.

**Comment by rbonilla31** [comment]
Hi, you should try to avoid keyCode in key events, instead use simply key. KeyCode is deprecated. Good job

**Comment by algismo** [comment]
Hi,

correct, I see that. Blindly copied "enter key" check. I will update both.

A side question. I did not manage to find the "source" of the file "ext-bundle.min.js" (in svgeditor dist). Is it intentional? 

Algirdas

**Comment by algismo** [comment]
I did my changes. There is now a conflict due to your recent changes. Shall I incorporate those changes in my branch or you will do manual merge with conflict resolution?

**Comment by unocelli** [comment]
@algismo Hi, I have to look and maybe do some modifications, I would appreciate if you could make the PR to the branch issue-451 that I just created.

**Comment by algismo** [comment]
Hi. I am not sure what to do :). Some days ago you did a merge into my branch "@unocelli
[Merge branch 'master' into issue-451](https://github.com/frangoteam/FUXA/pull/463/commits/f02f3fc9f2604cdabbeaf2c2e51633666642c2cd)". Now there are no conflicts so PR can be merged into master. Are there any other issues?

**Pull request merged**
