### PR TITLE
New Feature - Ability to access historical tags in script

### PR DESCRIPTION
**Pull request by adnanebrahimi**
**Describe the feature**
This is a missed feature for the script engine to access historical tags in the script. 
by accessing historical tags in the script, you can now calculate historical data and show them in the view.

**Describe the solution you'd like**

Creating a new system function` $getHistoricalTags` that accepts three arguments:

1. Array of historical Tags
2. Date for past date
3. Date for recent date

**Usage:**
`console.log(await $getHistoricalTags(['t_7b1017a7-10924aca','t_5ed33907-40b642d3'],'2024/06/01 - 00:00:00','2024/06/30 - 23:59:59'));`

With this line of code, you will get historical data for June

Or you can get historical data until present time by passing **empty string** like this:

`console.log(await $getHistoricalTags(['t_7b1017a7-10924aca','t_5ed33907-40b642d3'],'2024/06/01 - 00:00:00',''));`

**Output**:

```json
{
  "t_7b1017a7-10924aca": [
    { "x": "2024-06-30T20:30:00.000Z", "y": "1"},
    { "x": "2024-07-09T13:08:45.822Z", "y": "0" }
   ],
    "t_5ed33907-40b642d3": [
    { "x": "2024-06-30T20:30:00.000Z", "y": "0" },
    { "x": "2024-07-09T13:08:45.822Z", "y": "0" }
  ]
}
```

### CODE REVIEW

**Comment by unocelli** [comment]
Good work! I'm reviewing your PR.

**Comment by unocelli** [comment]
Hi, in pr1283 branch I made a few changes, in particular the Date format is not compatible for internationality.
I hope you don't mind, please give me a feedback.

**Comment by adnanebrahimi** [comment]
> Hi, in pr1283 branch I made a few changes, in particular the Date format is not compatible for internationality. I hope you don't mind, please give me a feedback.

I will check it. Thank you for the review.

**Comment by adnanebrahimi** [comment]
@unocelli 
It's working as expected 👍
In the deviceTagsSelectionComponent dialog, we added some changes that will list only historical tags if it is called in the getHistoricalTags function. it's not working. I will make new PR to fix it.

**Comment by unocelli** [comment]
I have forgotten, I will add it to the pr. Thanks a lot.

**Pull request merged**
