### PR TITLE
Fix Russian translation

### PR DESCRIPTION
**Pull request by Bykiev**
Fix Russian translation

### CODE REVIEW

**Comment by unocelli** [comment]
Hi, I'm looking your PR, and thanks for keeping the translation up to date.
I have only a question, the CustomMatPaginatorIntl component is the paginator with the translated texts?

**Comment by Bykiev** [comment]
Yes, to translate `mat-paginator` component a custom provider should be implemented. You can find more information about `MatPaginatorIntl` [here](https://material.angular.io/components/paginator/api#MatPaginatorIntl)

**Comment by unocelli** [comment]
Perfect, great job :D

**Comment by Bykiev** [comment]
Thanks!

**Pull request merged**
