### PR TITLE
Create settings for custom logo displayed in side bar

### PR DESCRIPTION
**Pull request by mauroalexandre**
Create a option in layout settings to user change default "Fuxa" text in side bar to a custom logo (resource).

### CODE REVIEW

**Comment by unocelli** [comment]
Great job, thanks a lot. I think I will move the settings into the header navigation tab, is more appropriate.

**Comment by haitan981** [comment]
I can't find a directory like yours to edit when I installed by 2 ways below:
- Install from [NPM](https://www.npmjs.com/package/@frangoteam/fuxa) (first option)

npm install -g --unsafe-perm @frangoteam/fuxa
fuxa

- Or in linux running from docker (third option)

docker pull frangoteam/fuxa:latest
docker run -d -p 1881:1881 frangoteam/fuxa:latest

// persistent storage of application data (project), daq (tags history) and logs
docker run -d -p 1881:1881 -v fuxa_appdata:/usr/src/app/FUXA/server/_appdata -v fuxa_db:/usr/src/app/FUXA/server/_db -v fuxa_logs:/usr/src/app/FUXA/server/_logs frangoteam/fuxa:latest

**Comment by mauroalexandre** [comment]
The settings is now avalaible in "Header Navigation Bar" tab. Please check.

**Comment by haitan981** [comment]
I don't see any change
image

**Comment by unocelli** [comment]
sorry, my mistake...I moved to 'Navigation Side Menu'
image

**Comment by haitan981** [comment]
How to change files like yours when I install FUXA with the command 
npm install -g --unsafe-perm @frangoteam/fuxa
fuxa
Following the below path, I don't see any client folder, only assets folder
C:\Users\haitan981\AppData\Roaming\npm\node_modules\@frangoteam\fuxa

**Pull request merged**
